version: '3'

services:
  web:
    build: .
    command: bash -c "python ./restapis/drf/todolist_api/manage.py makemigrations
             && python ./restapis/drf/todolist_api/manage.py migrate
             && python ./restapis/drf/todolist_api/manage.py runserver 0.0.0.0:8000"
    container_name: todoapp
    volumes:
      - .:/todoapp
    ports:
      - "8000:8000"